version: '2'

services:
  webapp:
    image: ubuntudesign/django-app:v1.0.3
    ports:
      - ${PORT}:5000
    volumes:
      - ${WORKDIR}:/app
      - dependencies:/usr/local/lib/python2.7/site-packages
    env_file: /.env

volumes:
  dependencies:
    driver: local
