version: '2'

services:
  webapp:
    image: ubuntudesign/django-app:v1.0.5
    ports:
      - ${PORT}:5000
    volumes:
      - ${WORKDIR}:/app
      - dependencies:/usr/local/lib/python2.7/site-packages
    environment:
      - DJANGO_DEBUG=true
      - SECRET_KEY=no_secret
    env_file: /.env

volumes:
  dependencies:
    driver: local

