version: '2'

services:
  webapp:
    extends:
      file: docker-compose.yml
      service: webapp
    links:
      - db

  watch-css:
    extends:
      file: docker-compose.yml
      service: watch-css

  db:
    image: postgres

  db-client:
    image: postgres
    links:
      - db
    command: bash -c "until psql -h db -U postgres; do echo 'Waiting 2 seconds...'; sleep 2; done"

volumes:
  dependencies:
    driver: local
