version: "2"
services:
  web:
    extends:
      file: docker-compose.devrun.yml
      service: web
    links: [db]

  db:
    image: postgres

  db-client:
    image: postgres
    links: [db]
    command: bash -c "until psql -h db -U postgres; do echo 'Waiting 2 seconds...'; sleep 2; done"
