version: '2'

services:
  webapp:
    image: ubuntudesign/django-app:v1.0.6
    ports:
      - ${PORT}:${PORT}
    volumes:
      - ${WORKDIR}:/app
      - dependencies:/usr/local/lib/python2.7/site-packages
    env_file: /.env
    environment:
      - PORT=${PORT}
      - DJANGO_DEBUG=${DJANGO_DEBUG}
      - SECRET_KEY=${SECRET_KEY}
  node:
    env_file: /.env
    image: ubuntudesign/node:v1.0.2
    volumes:
      - ${WORKDIR}:/app
      - npm-packages:/packages/node_modules
  watch-css:
    extends: node
    command: "npm run-script watch-css"

volumes:
  dependencies:
    driver: local
  npm-packages:
    driver: local
