version: "2"
services:
  base:
    image: ubuntu:14.04
    working_dir: /srv
    volumes: ["${WORKDIR}:/srv"]

  web:
    extends: {'service': 'base'}
    build: .
    ports: ["${PORT}:5000"]
    links: [db]
    env_file: "${WORKDIR}/.env"

  db:
    image: postgres

  db-client:
    image: postgres
    links: [db]
    command: bash -c "until psql -h db -U postgres; do echo 'Waiting 2 seconds...'; sleep 2; done"
